### ISSUE TITLE
More Assets for README

### ISSUE THREAD

**Issue by zettlunic** [kiselli/Lock.app#4]
![screen shot 2015-01-15 at 19 33 42](https://cloud.githubusercontent.com/assets/2598984/5763778/8b8be754-9ced-11e4-817d-7ce505b4a8a3.png)

**Comment by zettlunic** [comment]
![screen shot 2015-01-15 at 19 33 42](https://cloud.githubusercontent.com/assets/2598984/5763790/a0f562d2-9ced-11e4-82bd-4f105ae678aa.png)

**Comment by obuchmann** [comment]
:+1:
